// @flow
import { StyleSheet, Platform } from 'react-native';
import { isiPhone, isTablet } from '../utils';
import colors from './colors';

const styles: Object = StyleSheet.create({
  container: {
    flex: 1,
    marginVertical: 0,
    marginHorizontal: '5%',
    backgroundColor: colors.primaryDark,
  },
  ads: {
    position: 'absolute',
    bottom: isiPhone ? '4.5%' : 0,
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    width: '100%',
    height: '10%',
    zIndex: 999,
  },
  adSpace: {
    width: '100%',
    height: Platform.OS === 'ios' ? '10%' : '14%',
    backgroundColor: colors.black,
  },
  topWrapper: {
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    width: '100%',
    height: '60%',
    marginTop: Platform.isPad ? '2%' : '0',
    // backgroundColor: colors.black,
  },
  bottomWrapper: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: '100%',
    flex: 1,
  },
  screenMenuWrapper: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    marginTop: isiPhone ? '15%' : '2%',
  },
  navigationMenu: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: !isTablet ? '8%' : '6%',
    width: !isTablet ? '100%' : '80%',
    // backgroundColor: colors.black,
  },
  logo: {
    height: '100%',
    aspectRatio: 2 / 1,
  },
  menu: {
    height: '120%',
    aspectRatio: 1 / 2,
    // marginTop: "40%",
  },
  menuCloseW: {
    height: '80%',
    aspectRatio: 1 / 2,
  },
  menuClose: {
    height: '100%',
    aspectRatio: 1 / 2,
  },
  btnRewardScreen: {
    borderRadius: 15,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 3,
    borderLeftColor: colors.grayBlue,
    borderRightColor: colors.grayBlue,
    borderBottomColor: colors.grayBlue,
    backgroundColor: colors.primaryDark,
    paddingVertical: 8,
    paddingHorizontal: 15,
    marginBottom: '15%',
  },
  btnRewardScreenText: {
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 20,
    textAlign: 'center',
    color: colors.white,
  },
  btnRewardScreenDisabled: {
    borderRadius: 15,
    borderBottomWidth: 0,
    borderColor: colors.grayBlue,
    backgroundColor: colors.grayBlue,
    paddingVertical: 8,
    paddingHorizontal: 15,
    marginBottom: '15%',
  },
  btnRewardScreenTextDisabled: {
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 20,
    textAlign: 'center',
    color: colors.white,
  },
  menuWrapper: {
    width: !isTablet ? '100%' : '80%',
    flex: !isTablet ? 1 : 1 / 1.2,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  menuTitle: {
    fontFamily: 'Montserrat-SemiBold',
    textTransform: 'uppercase',
    fontSize: 20,
    textAlign: 'left',
    color: colors.primaryDark,
    marginRight: 10,
    marginBottom: 10,
  },
  bpmWrapper: {
    flexShrink: 1,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginTop: '5%',
  },
  inputBPM: {
    fontFamily: 'Montserrat-SemiBold',
    textTransform: 'uppercase',
    fontSize: 24,
    textAlign: 'center',
    color: colors.grayBlue,
    width: 120,
    height: 40,
    backgroundColor: colors.grayLight,
    borderRadius: 15,
  },
  radioWrapper: {
    flexGrow: 1 / 5,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  radioCont: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  radioText: {
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 24,
    textAlign: 'center',
    color: colors.grayBlue,
    marginRight: 14,
  },
  radioSelected: {
    width: 30,
    aspectRatio: 1 / 1,
    borderRadius: 30 / 2,
    backgroundColor: colors.primaryDark,
  },
  radioNotSelected: {
    width: 30,
    aspectRatio: 1 / 1,
    borderRadius: 30 / 2,
    backgroundColor: colors.grayLight,
  },
  rewardedWrapper: {
    flex: 1,
    width: !isTablet ? '100%' : '80%',
    marginVertical: !isTablet ? null : '2%',
    marginHorizontal: !isTablet ? null : '10%',
    display: 'flex',
    alignItems: 'center',
    backgroundColor: colors.primaryDark,
  },
  exit: {
    position: 'absolute',
    top: '3%',
    right: 0,
    width: 30,
    aspectRatio: 1 / 1,
  },
  countdownCon: {
    marginTop: '2%',
    width: '70%',
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: colors.primary,
  },
  countdownTimer: {
    fontFamily: 'Montserrat-SemiBold',
    textAlign: 'center',
    fontSize: 22,
    color: colors.gray,
    marginBottom: 5,
  },
  countdownTxt: {
    fontFamily: 'Montserrat-SemiBold',
    textAlign: 'center',
    fontSize: 12,
    color: colors.grayLight,
  },
  rewardedCon: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  rewardedExp: {
    marginTop: '10%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  rewardedExpText: {
    color: colors.gray,
    textAlign: 'center',
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 22,
    marginVertical: 2,
  },
  rewardedExp2Text: {
    fontFamily: 'Montserrat-SemiBold',
    textAlign: 'center',
    fontSize: 14,
    color: colors.gray,
    marginVertical: '20%',
  },
  rewardedStart: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.orange,
    width: 240,
    height: 50,
    borderRadius: 15,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 3,
    borderLeftColor: colors.orangeDark,
    borderRightColor: colors.orangeDark,
    borderBottomColor: colors.orangeDark,
    marginBottom: 20,
  },
  rewardedDisabled: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.orangeDark,
    width: 240,
    height: 50,
    borderRadius: 15,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 3,
    borderLeftColor: colors.orangeDark,
    borderRightColor: colors.orangeDark,
    borderBottomColor: colors.orangeDark,
    marginBottom: 20,
  },
  rewardedStartText: {
    color: colors.primaryDark,
    textAlign: 'center',
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 20,
  },
  rewardedDisc: {
    color: colors.grayLight,
    textAlign: 'center',
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 12,
  },
  selectReward: {
    flexShrink: 1,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '10%',
  },
  rewardTitle: {
    fontFamily: 'Montserrat-SemiBold',
    color: colors.gray,
    textAlign: 'right',
    fontSize: 14,
    marginTop: 40,
  },
  selectRewardInput: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: 240,
    height: 30,
    backgroundColor: colors.grayLight,
    borderRadius: 10,
    marginTop: 20,
  },
  selectRewardInputText: {
    fontFamily: 'Montserrat-SemiBold',
    color: colors.grayBlue,
    textAlign: 'right',
    fontSize: 18,
  },
  selectRewardListArrow: {
    position: 'absolute',
    right: 10,
    width: 20,
    aspectRatio: 1 / 1,
  },
  modalView: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: !isTablet ? '90%' : '70%',
    marginTop: !isTablet ? '30%' : '20%',
    marginHorizontal: !isTablet ? '5%' : '15%',
    paddingVertical: 15,
    paddingHorizontal: 10,
    backgroundColor: colors.primary,
    borderRadius: 30,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
    zIndex: 5,
  },
  modalTxt: {
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 14,
    textAlign: 'center',
    color: colors.grayLight,
  },
  modalExp: {
    fontFamily: 'Montserrat-SemiBold',
    color: colors.gray,
    textAlign: 'center',
    fontSize: 12,
    marginHorizontal: 10,
    marginBottom: 16,
  },
  inputMidi: {
    width: '100%',
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 18,
    textAlign: 'left',
    color: colors.grayBlue,
    backgroundColor: colors.grayLight,
    borderRadius: 20,
    paddingVertical: 5,
    paddingHorizontal: 10,
    marginVertical: 15,
  },
  modalBtnCont: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalBtn: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '30%',
    height: 30,
    backgroundColor: colors.grayLight,
    borderRadius: 30,
    marginHorizontal: 10,
  },
  modalBtnTxt: {
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 16,
    textAlign: 'center',
    color: colors.primaryDark,
  },
});

export default styles;
