require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'Ritmo' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'react-native-in-app-review', :path => '../node_modules/react-native-in-app-review'
  
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'RitmoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end
end
