// @flow
import type { Beat } from '../store/beatsStore';

type Beats = {
  hihat: Beat[],
  snare: Beat[],
  kick: Beat[],
};

const beats: Beats = {
  hihat: [
    {
      checked: false,
      timeSig: 'Free',
      visible: true,
      angle: 0,
      initAngle: 0,
      soundName: 'HiHat.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 30,
      initAngle: 30,
      soundName: 'HiHat.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '4/4',
      visible: true,
      angle: 45,
      initAngle: 45,
      soundName: 'HiHat.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 60,
      initAngle: 60,
      soundName: 'HiHat.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: 'Free',
      visible: true,
      angle: 90,
      initAngle: 90,
      soundName: 'HiHat.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 120,
      initAngle: 120,
      soundName: 'HiHat.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '4/4',
      visible: true,
      angle: 135,
      initAngle: 135,
      soundName: 'HiHat.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 150,
      initAngle: 150,
      soundName: 'HiHat.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: 'Free',
      visible: true,
      angle: 180,
      initAngle: 180,
      soundName: 'HiHat.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 210,
      initAngle: 210,
      soundName: 'HiHat.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '4/4',
      visible: true,
      angle: 225,
      initAngle: 225,
      soundName: 'HiHat.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 240,
      initAngle: 240,
      soundName: 'HiHat.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: 'Free',
      visible: true,
      angle: 270,
      initAngle: 270,
      soundName: 'HiHat.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 300,
      initAngle: 300,
      soundName: 'HiHat.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '4/4',
      visible: true,
      angle: 315,
      initAngle: 315,
      soundName: 'HiHat.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 330,
      initAngle: 330,
      soundName: 'HiHat.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
  ],
  snare: [
    {
      checked: false,
      timeSig: 'Free',
      visible: true,
      angle: 0,
      initAngle: 0,
      soundName: 'Snare.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 30,
      initAngle: 30,
      soundName: 'Snare.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '4/4',
      visible: true,
      angle: 45,
      initAngle: 45,
      soundName: 'Snare.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 60,
      initAngle: 60,
      soundName: 'Snare.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: 'Free',
      visible: true,
      angle: 90,
      initAngle: 90,
      soundName: 'Snare.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 120,
      initAngle: 120,
      soundName: 'Snare.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '4/4',
      visible: true,
      angle: 135,
      initAngle: 135,
      soundName: 'Snare.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 150,
      initAngle: 150,
      soundName: 'Snare.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: 'Free',
      visible: true,
      angle: 180,
      initAngle: 180,
      soundName: 'Snare.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 210,
      initAngle: 210,
      soundName: 'Snare.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '4/4',
      visible: true,
      angle: 225,
      initAngle: 225,
      soundName: 'Snare.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 240,
      initAngle: 240,
      soundName: 'Snare.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: 'Free',
      visible: true,
      angle: 270,
      initAngle: 270,
      soundName: 'Snare.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 300,
      initAngle: 300,
      soundName: 'Snare.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '4/4',
      visible: true,
      angle: 315,
      initAngle: 315,
      soundName: 'Snare.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 330,
      initAngle: 330,
      soundName: 'Snare.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
  ],
  kick: [
    {
      checked: false,
      timeSig: 'Free',
      visible: true,
      angle: 0,
      initAngle: 0,
      soundName: 'Kick.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 30,
      initAngle: 30,
      soundName: 'Kick.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '4/4',
      visible: true,
      angle: 45,
      initAngle: 45,
      soundName: 'Kick.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 60,
      initAngle: 60,
      soundName: 'Kick.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: 'Free',
      visible: true,
      angle: 90,
      initAngle: 90,
      soundName: 'Kick.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 120,
      initAngle: 120,
      soundName: 'Kick.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '4/4',
      visible: true,
      angle: 135,
      initAngle: 135,
      soundName: 'Kick.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 150,
      initAngle: 150,
      soundName: 'Kick.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: 'Free',
      visible: true,
      angle: 180,
      initAngle: 180,
      soundName: 'Kick.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 210,
      initAngle: 210,
      soundName: 'Kick.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '4/4',
      visible: true,
      angle: 225,
      initAngle: 225,
      soundName: 'Kick.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 240,
      initAngle: 240,
      soundName: 'Kick.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: 'Free',
      visible: true,
      angle: 270,
      initAngle: 270,
      soundName: 'Kick.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 300,
      initAngle: 300,
      soundName: 'Kick.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '4/4',
      visible: true,
      angle: 315,
      initAngle: 315,
      soundName: 'Kick.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
    {
      checked: false,
      timeSig: '3/4',
      visible: true,
      angle: 330,
      initAngle: 330,
      soundName: 'Kick.mp3',
      soundDelay: 0,
      soundDelayKey: '_timeout',
    },
  ],
};

export default beats;
